language: elixir
elixir:
  - 1.6.2
otp_releases:
  - 20.0
sudo: false
env:
  install:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix deps.compile
  script:
    - mix format --check-formatted --check-equivalent --dry-run
    - mix test
  notifications:
    - jangelod@gmail.com

