language: elixir
elixir:
  - 1.5.1
  - 1.5.3
otp_releases:
  - 19.0
  - 20.0
sudo: false
env:
  install:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get
    - mix deps.compile
  script:
    - mix format --check-formatted --check-equivalent --dry-run
    - mix test
  notifications:
    - jangelod@gmail.com

