#!/bin/bash

PROTO=http
HOST=localhost
PORT=4000
API=api/v1
URL=$PROTO://$HOST:$PORT/$API
TO=99999

function addFile {
  curl -vX POST $URL/torrent/addFile \
    -H "Content-Type: application/json" \
    -d '{"filename":"priv/'${1}'.torrent"}' \
    --connect-timeout $TO
}

function connectToTracker {
  curl -vX PUT $URL/torrent/$1/connect/ \
  --connect-timeout $TO
}

function connectToTrackerAsync {
  curl -vX PUT $URL/torrent/$1/connect/async \
  --connect-timeout $TO
}

function startTorrent {
    curl -vX PUT $URL/torrent/$1/startTorrent \
    --connect-timeout $TO
}

function startTorrentAsync {
    curl -vX PUT $URL/torrent/$1/startTorrent/async \
    --connect-timeout $TO
}

function listAll {
  curl -vX GET $URL/torrent \
  --connect-timeout $TO
}

function removeall {
  curl -vX DELETE $URL/torrent/removeAll \
  --connect-timeout $TO
}

function removeTorrent {
  curl -vX DELETE $URL/torrent/$1/remove \
}

function getStatus {
  curl -vX GET $URL/torrent/$1/status \
  --connect-timeout $TO
}

function getInfo {
  curl -vX GET $URL/$1/info \
  --connect-timeout $TO
}
