#!/bin/bash

PROTO=http
HOST=localhost
PORT=8080
API=api/v1
URL=$PROTO://$HOST:$PORT/$API

function addFile {
  curl -vX POST $URL/add/file \
    -H "Content-Type: application/json" \
    -d '{"filename":"priv/'${1}'.torrent"}' 
}

function connectToTracker {
  curl -vX PUT $URL/$1/connect/
}

function connectToTrackerAsync {
  curl -vX PUT $URL/$1/connect/async
}

function startTorrent {
    curl -vX PUT $URL/$1/startTorrent/
}

function startTorrentAsync {
    curl -vX PUT $URL/$1/startTorrent/async
}

function listAll {
  curl -vX GET $URL/all
}

function removeall {
  curl -vX DELETE $URL/remove/all
}

function removeTorrent {
  curl -vX DELETE $URL/$1/remove/
}

function getStatus {
  curl -vX GET $URL/$1/status
}

function getInfo {
  curl -vX GET $URL/$1/info
}
