use Mix.Config
config :bittorrent_client,
  peer_id: "-ET0001-aaaaaaaaaaaa",
  compact: 1,
  port: 36562,
  no_peer_id: 0,
  ip: "127.0.0.1",
  numwant: 80,
  key: "",
  trackerid: "",
  server_impl: BittorrentClient.Server.GenServerImpl
